jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (private repo)
        uses: actions/checkout@v4

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v44.0.5
        with:
          configurationFile: .github/renovate.json5
          token: ${{ secrets.RENOVATE_TOKEN }}
        env:
          RENOVATE_REPOSITORIES: slapah/my-graphene-releases
          LOG_LEVEL: ${{ inputs.logLevel || 'debug' }}
